version: '3.9'

services:
  app:
    build: .
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis

  redis:
    image: "redis:6-alpine"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
